Composable + store
HALWAAAAA/vue-project-shop pull request #4
Opened 2024-11-25 17:22 UTC by HALWAAAAA

Ну кароче, почистив код, забрав все, що лишнє й непотрібне. Далі, addToCart додав до стора, removeFromCart видалив, бо addTOCart уніваерсальна. Було довго, довго з тим грався, але було цікаво, як то зробити. 
Також зробив openDrawer, closeDrawer Composable, трохи зробив дивно, бо це у мене і як store, і як Composable. Тут я хз, чи добре зробив, бо самий вже я не дав ради тут, а чат так підказав, тому треба, щоб ти оцінив

2024-11-27 16:01 UTC, halws requested changes
додав пару уваг, але вже набагато чистіше ніж було

2024-11-27 16:01 UTC, halws commented on src/App.vue
> +import { useDrawerStore } from './Composable/useDrawer';
то вже зроби папку stores і то таки хай буде стор а не composable

2024-11-27 16:01 UTC, halws commented on src/App.vue
>  const updateCartItems = () => {
якщо це стосується чисто стору то винеси це в стор. старайся не мутувати елементи стору поза стором

2024-11-27 16:01 UTC, halws commented on src/App.vue
>  const totalPrice = computed(() => {
по суті це getter в сторі

2024-11-27 16:01 UTC, halws commented on src/App.vue
>  const totalPrice = computed(() => {
можна забрати в стор

2024-11-27 16:01 UTC, halws commented on src/Composable/useDrawer.js
> +export const useDrawerStore = defineStore('drawer', ()=>{
компосабл можня як міні стор використовувати https://dev.to/jacobandrewsky/sharing-composable-state-in-vue-apps-41l1

2024-11-27 16:01 UTC, halws commented on src/Header.vue
> +import { useDrawerStore } from './Composable/useDrawer';
якщо це composalbe то не називай його стор
`useDrawer` цього буде достатньо

2024-11-27 16:01 UTC, halws commented on src/components/Card.vue
> +      @click=""
чому пустий?

2024-11-27 16:01 UTC, halws commented on src/components/Card.vue
> +const currentItem = computed(() => items.value.find((item) => item.id === props.id)|| {});
або ще можна просто в prop кидати item і так і так норм

проте якщо в prop то це краще щоб потім тести писати

2024-11-27 16:01 UTC, halws commented on src/components/CardList.vue
>        :id="item.id"
завжди додаввай key для for елементів

2024-11-27 16:01 UTC, halws commented on src/components/CardList.vue
>        :id="item.id"
https://vuejs.org/style-guide/rules-essential.html#use-keyed-v-for

2024-11-27 16:01 UTC, halws commented on src/components/CardList.vue
>        :id="item.id"
рекомендую ознайомитися https://vuejs.org/style-guide/#style-guide

2024-11-27 16:05 UTC, halws commented
> addToCart додав до стора, removeFromCart

краще зробити 2 методи, так очевидніше що воно робить

2024-11-27 16:08 UTC, halws commented on src/Composable/useDrawer.js
> +export const useDrawerStore = defineStore('drawer', ()=>{
тому defineStore('drawer', тут лишній

2024-11-27 16:10 UTC, halws commented on src/Composable/useDrawer.js
> +  return {drawerOpenData,openDrawer, closeDrawer };
```suggestion
  return {
  drawerOpenData : readonly(drawerOpenData), // https://vuejs.org/api/reactivity-core.html#readonly
  openDrawer,
   closeDrawer };
```

2024-11-27 16:13 UTC, halws commented on src/components/Card.vue
> -  imageUrl: String,
коли ти передаєш багато пропсів які по суті можна в 1 обʼєкті то це погано, краще одним обʼєктом як в тому патерні описано https://www.notion.so/Vue-patterns-122b9fa51f27800d9074cdd567291072?pvs=4#14ab9fa51f2780ee931ff6fe892422b5

2024-12-03 14:27 UTC, HALWAAAAA commented on src/components/CardList.vue
>        :id="item.id"
я просто думав, що :id="item.id" може виконувати ту саму функцію, що і 🔑 . Добавив

2024-12-03 17:43 UTC, halws approved these changes
LGTM

2024-12-03 17:43 UTC, merged